remind_reservations_mail_job:
  cron: "0 10 * * *"
  class: RemindReservationsMailJob
  queue: default

remind_reservation_payments_job:
  cron: "0 10 * * *"
  class: RemindReservationPaymentsJob
  queue: default

update_all_reservation_payment_status_job:
  cron: "*/10 * * * *"
  class: UpdateAllReservationPaymentStatusJob
  queue: default

replace_expired_reservation_payments_job:
  cron: "3 * * * *"
  class: ReplaceExpiredReservationPaymentsJob
  queue: default

clear_cache_job:
  cron: "0 0 * * *"
  class: ClearCacheJob
  queue: default
